dataSources:
  ds-user:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
#    jdbcUrl: jdbc:mysql://mysql:3306/mall_customer?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    jdbcUrl: jdbc:mysql://localhost:3306/mall_customer_dev?characterEncoding=utf-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useSSL=false

rules:
  - !ENCRYPT
    encryptors:
      customer-user-encryptor:
        props:
          aes-key-value: ADbisulBtxnnKFoW
        type: AES
    tables:
      customer_user:
        columns:
          mail:
            cipher:
              name: mail
              encryptorName: customer-user-encryptor
          phone:
            cipher:
              name: phone
              encryptorName: customer-user-encryptor
      receive_address:
        columns:
          phone:
            cipher:
              name: phone
              encryptorName: customer-user-encryptor
          detail_address:
            cipher:
              name: detail_address
              encryptorName: customer-user-encryptor
  - !SHARDING
    shardingAlgorithms:
      customer_user_sharding_by_mod:
        type: INLINE
        props:
          algorithm-expression: customer_user_${id % 16}
      operation_log_sharding_by_mod:
        type: INLINE
        props:
          algorithm-expression: operation_log_${customer_user_id % 16}
      receive_address_sharding_by_mod:
        type: INLINE
        props:
          algorithm-expression: receive_address_${customer_user_id % 16}
    tables:
      customer_user:
        actualDataNodes: ds-user.customer_user_${0..15}
        tableStrategy:
          standard:
            shardingAlgorithmName: customer_user_sharding_by_mod
            shardingColumn: id
      operation_log:
        actualDataNodes: ds-user.operation_log_${0..15}
        tableStrategy:
          standard:
            shardingAlgorithmName: operation_log_sharding_by_mod
            shardingColumn: customer_user_id
      receive_address:
        actualDataNodes: ds-user.receive_address_${0..15}
        tableStrategy:
          standard:
            shardingAlgorithmName: receive_address_sharding_by_mod
            shardingColumn: customer_user_id

props:
  sql-show: true
