dataSources:
  ds-cart: # 购物车库
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
#    jdbcUrl: jdbc:mysql://mysql:3306/mall_cart?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    jdbcUrl: jdbc:mysql://localhost:3306/mall_cart_dev?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true

rules:
  - !SHARDING
    shardingAlgorithms:
      cart-item_sharding_by_mod:
        type: INLINE
        props:
          algorithm-expression: cart_item_${customer_user_id % 16}
    tables:
      cart_item:
        actualDataNodes: ds-cart.cart_item_${0..15}
        tableStrategy:
          standard:
            shardingAlgorithmName: cart-item_sharding_by_mod
            shardingColumn: customer_user_id

transaction:
  # 将默认事务设为 BASE，这样只要方法加了 Spring 的 @Transactional，就会自动切换到 Seata
  defaultType: BASE
  providerType: Seata

props:
  sql-show: true