dataSources:
  ds-order:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
#    jdbcUrl: jdbc:mysql://mysql:3306/mall_order?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    jdbcUrl: jdbc:mysql://localhost:3306/mall_order_dev?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true

rules:
  - !SHARDING
    tables:
      order_info:
        actualDataNodes: ds-order.order_info_${0..15}
        tableStrategy:
          complex:
            shardingAlgorithmName: order_snowflake-service_algorithm
            shardingColumns: customer_user_id,order_sn
      order_item:
        actualDataNodes: ds-order.order_item_${0..15}
        tableStrategy:
          complex:
            shardingAlgorithmName: order_snowflake-service_algorithm
            shardingColumns: customer_user_id,order_sn
    shardingAlgorithms:
      order-item_sharding_by_mod:
        props:
          algorithmClassName: com.noinch.mall.biz.order.infrastructure.algorithm.OrderSnowflakeServiceShardingAlgorithm
          sharding-count: 16
          strategy: complex
        type: CLASS_BASED
      order_snowflake-service_algorithm:
        props:
          algorithmClassName: com.noinch.mall.biz.order.infrastructure.algorithm.OrderSnowflakeServiceShardingAlgorithm
          sharding-count: 16
          strategy: complex
        type: CLASS_BASED

transaction:
  # 将默认事务设为 BASE，这样只要方法加了 Spring 的 @Transactional，就会自动切换到 Seata
  defaultType: BASE
  providerType: Seata

props:
  sql-show: true