dataSources:
  ds-product:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
#    jdbcUrl: jdbc:mysql://mysql:3306/mall_product?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    jdbcUrl: jdbc:mysql://localhost:3306/mall_product_dev?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true

rules:
  # 广播表
  - !BROADCAST
    tables:
      - product_attribute
      - product_attribute_category
      - product_attribute_value
      - product_brand
      - product_category
  # 分片表
  - !SHARDING
    tables:
      product_spu:
        actualDataNodes: ds-product.product_spu_${0..15}
        tableStrategy:
          complex:
            shardingAlgorithmName: product-spu_sharding_by_mod_algorithm
            shardingColumns: brand_id,id
      product_sku:
        actualDataNodes: ds-product.product_sku_${0..15}
        tableStrategy:
          complex:
            shardingAlgorithmName: product-sku_sharding_by_mod_algorithm
            shardingColumns: brand_id,product_id
      product_comment:
        actualDataNodes: ds-product.product_comment_${0..15}
        tableStrategy:
          standard:
            shardingAlgorithmName: product-comment_sharding_by_mod
            shardingColumn: product_id
    shardingAlgorithms:
      product-spu_sharding_by_mod_algorithm:
        props:
          algorithmClassName: com.noinch.mall.biz.product.infrastructure.algorithm.ProductSpuSnowflakeServiceShardingAlgorithm
          sharding-count: 16
          strategy: complex
        type: CLASS_BASED
      product-sku_sharding_by_mod_algorithm:
        props:
          algorithmClassName: com.noinch.mall.biz.product.infrastructure.algorithm.ProductSkuSnowflakeServiceShardingAlgorithm
          sharding-count: 16
          strategy: complex
        type: CLASS_BASED
      product-comment_sharding_by_mod:
        type: INLINE
        props:
          algorithm-expression: product_comment_${product_id % 16}

transaction:
  # 将默认事务设为 BASE，这样只要方法加了 Spring 的 @Transactional，就会自动切换到 Seata
  defaultType: BASE
  providerType: Seata

props:
  sql-show: true