dataSources:
  ds-message:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
#    jdbcUrl: jdbc:mysql://mysql:3306/mall_message?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    jdbcUrl: jdbc:mysql://localhost:3306/mall_message_dev?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true

rules:
  - !BROADCAST
    tables:
      - mail_template
  - !SHARDING
    tables:
      send_record:
        actualDataNodes: ds-message.send_record_${2023..2026}_m${1..12}
        tableStrategy:
          complex:
            shardingAlgorithmName: message-snowflake_date_algorithm
            shardingColumns: create_time,msg_id
      send_record_extend:
        actualDataNodes: ds-message.send_record_extend_${2023..2026}_m${1..12}
        tableStrategy:
          complex:
            shardingAlgorithmName: message-snowflake_date_algorithm
            shardingColumns: create_time,msg_id
    shardingAlgorithms:
      message-snowflake_date_algorithm:
        props:
          algorithmClassName: com.noinch.mall.biz.message.infrastructure.algorithm.SnowflakeDateShardingAlgorithm
          strategy: complex
        type: CLASS_BASED


props:
  sql-show: true